#change "path" values to match your configuration
scripts:
  path: /path/to/scripts
  commands:
    new: create_new_repo.sh
    delete: delete_repo.sh
    sync: rsync_to_webtest.sh
repos:
  path: /path/to/repos
webtests:
  host: localhost
  path: /path/to/webtests

